name: Build Release

on:
  release:
    types: [ created ]

jobs:
  build_desktop_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Generate runtime
        run: cd desktop && jlink --output ./runtime/ --no-man-pages --no-header-files --add-modules java.base,java.desktop,java.sql,java.net.http,jdk.crypto.ec --compress=2

      - name: Copy libraries
        run: cd desktop && mvn dependency:copy-dependencies -DincludeScope=runtime -DoutputDirectory=resources

      - name: Create jar
        run: cd desktop && mvn package && move target/PDFTableExtractor-1.0.jar resources/PDFTableExtractor.jar

      - name: Create installer
        run: cd desktop && jpackage --runtime-image runtime --input resources --main-class pdftableextractordesktop.Main --main-jar PDFTableExtractor.jar --name PDFTableExtractor --vendor Degubi --description PDFTableExtractor --icon icon.ico --win-per-user-install --win-dir-chooser --win-shortcut --win-console

      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: desktop/PDFTableExtractor-1.0.exe
          asset_name: PDFTableExtractor.exe
          tag: ${{ github.ref }}

  build_desktop_linux:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - name: Set up Java
          uses: actions/setup-java@v1
          with:
            java-version: 21

        - name: Generate runtime
          run: cd desktop && jlink --output ./runtime/ --no-man-pages --no-header-files --add-modules java.base,java.desktop,java.sql,java.net.http,jdk.crypto.ec --compress=2

        - name: Copy libraries
          run: cd desktop && mvn dependency:copy-dependencies -DincludeScope=runtime -DoutputDirectory=resources

        - name: Create jar
          run: cd desktop && mvn package && move target/PDFTableExtractor-1.0.jar resources/PDFTableExtractor.jar

        - name: Create installer
          run: cd desktop && jpackage --runtime-image runtime --input resources --main-class pdftableextractordesktop.Main --main-jar PDFTableExtractor.jar --name PDFTableExtractor --vendor Degubi --description PDFTableExtractor --icon icon.ico --linux-shortcut

        - name: Upload binary to release
          uses: svenstaro/upload-release-action@v2
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: desktop/pdftableextractor_1.0_amd64.deb
            asset_name: PDFTableExtractor.deb
            tag: ${{ github.ref }}
